### ISSUE TITLE
React-group-project SpaceX-hub

### ISSUE THREAD

**Issue by gabrielcoder247** [gabrielcoder247/spaceX-Hub#49]
Hello Hacker,
This project is called spaceX-hub.
I and @Mucyosoda, Will be collaborating to build this project.
here' s a link to our project  [spaceX-hub](https://github.com/gabrielcoder247/spaceX-Hub/projects/1) or https://github.com/gabrielcoder247/spaceX-Hub/projects/1
The number of collaborators are 2.
Please, do a review and let us know.

Thanks and Happy Monday :grinning:

**Comment by dasileker** [comment]
### **Hi @gabrielcoder247,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- the link that you are supposed to add in your issue is the **Project** link to your kaban cards.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-labana** [comment]
Hi team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] Since you are a team of two collaborators all cards with Team3 prefix on the template should be removed (Each member should work on `Missions` or `Rockets` module, currently there are more cards than needed).
- [ ] There should be a total of cards 17 in the project board (currently there are 27). 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bellom** [comment]
Hello 👋,

This is an additional review as a result of the second opinion request.

Seems you guys missed part of the project requirements, with a team of 2, you're supposed to have 17 cards on your kanban board.

Kindly check out the below screenshot from the project requirements.
![image](https://user-images.githubusercontent.com/31897434/144018091-481e086a-0bba-41e5-a827-ccb8ff3bde5d.png)

Kindly make the necessary changes and request for re-review.

Keep rocking 🚀!
